services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DEBUG=0
      - DB_HOST=db
      - DB_NAME=postgresdevdb
      - DB_USER=devdbuser
      - DB_PASS=devdbpassword
      - SECRET_KEY=changeDevSecretKey
      - ALLOWED_HOSTS=localhost,0.0.0.0
      - CSRF_TRUSTED_ORIGINS=https://dev-be.domain.com
      - OPENAI_ORG_KEY=org-uniqueorgid
      - OPENAI_API_KEY=sk-uniqueprojectkey
      - AWS_ACCESS_KEY_ID=AwsAccessKeyId
      - AWS_SECRET_ACCESS_KEY=AwsSecretAccessKey
      - AWS_STORAGE_BUCKET_NAME=aws-storage-bucket-name
      - SENDGRID_API_KEY=SG.APIKey
      - SENDGRID_SENDER_EMAIL=admin@mailinator.com
      - SENDGRID_COMPANY_INFO_EMAIL=info@company.com
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=postgresdevdb
      - POSTGRES_USER=devdbuser
      - POSTGRES_PASSWORD=devdbpassword

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 8000:8000
    volumes:
      - static-data:/vol/static

volumes:
  postgres-dev-data:
  static-data:
