---
name: Checks

on: [push]

jobs:
    test-lint:
        name: Check for Test Cases and Lint Rules
        runs-on: ubuntu-20.04

        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Checkout
              uses: actions/checkout@v2
            - name: Test
              run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
            - name: Lint
              run: docker-compose run --rm app sh -c "flake8"
  
    codespell:
        name: Check for spelling errors
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Codespell
              uses: codespell-project/actions-codespell@v2
              with:
                skip: guide_imports.json
